### ISSUE TITLE
zsocket:recv() throws "attempt to call global 'zmq_recvmsg' (a nil value)"

### ISSUE THREAD

**Issue by 1linux** [Neopallium/lua-zmq#53]
I´m in Mac OSX 10.10.2, and using ZeroBraneStudio as my preferred IDE.
Inside ZBS you can easily install LuaDist packages.
I did on the console
`luadist.install("lua-zmq",{source=true, debug=true})`
This installs zmq 3.2.4 and lua-zmq.1.1
Running the following code throws the error above:

```
local zmq = require"zmq"
local ctx = zmq.init(5)
local s = ctx:socket(zmq.SUB)
s:setopt(zmq.SUBSCRIBE, "")
s:connect("tcp://localhost:5555")
while true do
    local msg = s:recv()
    local msg_id = tonumber(msg)
    if math.mod(msg_id, 10000) == 0 then print(msg_id) end
end
```

I´m using zmq for years now, code runs smoothly on both windows and linux.
Any ideas how to fix the issue?

**Comment by Neopallium** [comment]
lua-zmq verion 1.1 doesn't support zeromq 3.x.  I have added support in the newest code.

I am not sure when I will have time to roll new release right now.

**Comment by 1linux** [comment]
Really? I think it worked both on linux and windows...
